# Creating a vector of length 5 filled with random integers between 0 to 10

In [1]:
import numpy as np

In [2]:
vector = np.random.randint(0,11, size=5)

In [3]:
print(vector)

[3 4 7 0 3]


# Creating a vector with values ranging from 15 to 55 and printing all values except the first and last.

In [4]:
vector = np.arange(15, 56)

In [5]:
print(vector[1:-1])

[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]


# creating a random array with 1000 elements and computing the average, variance, standard deviation of the array elements. 

In [6]:
arr = np.random.rand(1000)

In [7]:
avg = np.mean(arr)

In [8]:
variance = np.var(arr)

In [9]:
std_dev = np.std(arr)

In [10]:
print("Average", avg)
print("Variance", variance)
print("Standard deviation", std_dev)

Average 0.4989161247626261
Variance 0.08332279429167397
Standard deviation 0.2886568798620154


# program to calculate cumulative sum of the elements along a given axis, sum over rows for each of the 3 columns and sum over columns for each of the 2 rows of a given 3x3 array. 

In [3]:
import numpy as np

In [4]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [5]:
print("Original array:\n", arr)

Original array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
cum_sum_axis0 = np.cumsum(arr, axis=0)

In [7]:
print("\ncumulative sum along axis 0:\n", cum_sum_axis0)


cumulative sum along axis 0:
 [[ 1  2  3]
 [ 5  7  9]
 [12 15 18]]


In [8]:
cum_sum_axis1 = np.cumsum(arr, axis=1)

In [9]:
print("\nCumulative sum along axis 1:\n",cum_sum_axis1)


Cumulative sum along axis 1:
 [[ 1  3  6]
 [ 4  9 15]
 [ 7 15 24]]


In [10]:
sum_rows_each_col = np.sum(arr, axis=0)
print("\nSum over rows for each column:\n", sum_rows_each_col)


Sum over rows for each column:
 [12 15 18]


In [11]:
sum_cols_each_row = np.sum(arr, axis=1)
print("\nSum over columns for each row:\n", sum_cols_each_row)


Sum over columns for each row:
 [ 6 15 24]


# NumPy program to compute the multiplication of two given matrixes. 

Sample Matrix: 

[[1, 0], [0, 1]] 

[[1, 2], [3, 4]] 

In [12]:
# Defining the matrices
matrix1 = np.array([[1, 0], [0, 1]])
matrix2 = np.array([[1, 2], [3, 4]])

In [13]:
# Multipying the matrices using the dot() function
result = np.dot(matrix1, matrix2)
print("The result of the multiplication is:")
print(result)

The result of the multiplication is:
[[1 2]
 [3 4]]
